#!/usr/bin/bash

LOCAL_DIST_DIR=dist
DIST_DIR=../

elm make src/Main.elm --optimize --output $LOCAL_DIST_DIR/js/vsh.js

cp $LOCAL_DIST_DIR/css/vsh.css $DIST_DIR/css/
cp $LOCAL_DIST_DIR/js/vsh.js $DIST_DIR/js/